name: Trigger Render Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'app.py'
      - 'mahjong_manager.py'
      - 'requirements.txt'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render Deploy Hook
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}